# uk-carbon-dashboard/docker-compose.yml

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    # --- ADD THIS HEALTHCHECK BLOCK ---
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    # --- MODIFY depends_on TO THIS MORE ADVANCED VERSION ---
    depends_on:
      backend:
        condition: service_healthy